package com.vitrocar.model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aseguradora generated by hbm2java
 */
public class Aseguradora  implements java.io.Serializable {


     private int idAseguradora;
     private String nombre;
     private Set<Siniestro> siniestros = new HashSet<Siniestro>(0);

    public Aseguradora() {
    }

	
    public Aseguradora(int idAseguradora) {
        this.idAseguradora = idAseguradora;
    }
    public Aseguradora(int idAseguradora, String nombre, Set<Siniestro> siniestros) {
       this.idAseguradora = idAseguradora;
       this.nombre = nombre;
       this.siniestros = siniestros;
    }
   
    public int getIdAseguradora() {
        return this.idAseguradora;
    }
    
    public void setIdAseguradora(int idAseguradora) {
        this.idAseguradora = idAseguradora;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Siniestro> getSiniestros() {
        return this.siniestros;
    }
    
    public void setSiniestros(Set<Siniestro> siniestros) {
        this.siniestros = siniestros;
    }




}


