package com.vitrocar.model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1



/**
 * AutoPieza generated by hbm2java
 */
public class AutoPieza  implements java.io.Serializable {


     private int idAutoPieza;
     private Auto auto;
     private Pieza pieza;

    public AutoPieza() {
    }

	
    public AutoPieza(int idAutoPieza) {
        this.idAutoPieza = idAutoPieza;
    }
    public AutoPieza(int idAutoPieza, Auto auto, Pieza pieza) {
       this.idAutoPieza = idAutoPieza;
       this.auto = auto;
       this.pieza = pieza;
    }
   
    public int getIdAutoPieza() {
        return this.idAutoPieza;
    }
    
    public void setIdAutoPieza(int idAutoPieza) {
        this.idAutoPieza = idAutoPieza;
    }
    public Auto getAuto() {
        return this.auto;
    }
    
    public void setAuto(Auto auto) {
        this.auto = auto;
    }
    public Pieza getPieza() {
        return this.pieza;
    }
    
    public void setPieza(Pieza pieza) {
        this.pieza = pieza;
    }




}


