package com.vitrocar.model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1



/**
 * Facturacion generated by hbm2java
 */
public class Facturacion  implements java.io.Serializable {


     private String rfc;
     private Cliente cliente;
     private Cp cp;
     private String razonSocial;
     private String correo;
     private String direccion;
     private Integer numero;
     private String colonia;
     private String localidad;

    public Facturacion() {
    }

	
    public Facturacion(String rfc) {
        this.rfc = rfc;
    }
    public Facturacion(String rfc, Cliente cliente, Cp cp, String razonSocial, String correo, String direccion, Integer numero, String colonia, String localidad) {
       this.rfc = rfc;
       this.cliente = cliente;
       this.cp = cp;
       this.razonSocial = razonSocial;
       this.correo = correo;
       this.direccion = direccion;
       this.numero = numero;
       this.colonia = colonia;
       this.localidad = localidad;
    }
   
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Cp getCp() {
        return this.cp;
    }
    
    public void setCp(Cp cp) {
        this.cp = cp;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }




}


