package com.vitrocar.model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Istable generated by hbm2java
 */
public class Istable  implements java.io.Serializable {


     private int idIpc;
     private OrdenServicio ordenServicio;
     private String observaciones;
     private Date fechaAtencion;
     private Date fechaEntrega;

    public Istable() {
    }

	
    public Istable(int idIpc) {
        this.idIpc = idIpc;
    }
    public Istable(int idIpc, OrdenServicio ordenServicio, String observaciones, Date fechaAtencion, Date fechaEntrega) {
       this.idIpc = idIpc;
       this.ordenServicio = ordenServicio;
       this.observaciones = observaciones;
       this.fechaAtencion = fechaAtencion;
       this.fechaEntrega = fechaEntrega;
    }
   
    public int getIdIpc() {
        return this.idIpc;
    }
    
    public void setIdIpc(int idIpc) {
        this.idIpc = idIpc;
    }
    public OrdenServicio getOrdenServicio() {
        return this.ordenServicio;
    }
    
    public void setOrdenServicio(OrdenServicio ordenServicio) {
        this.ordenServicio = ordenServicio;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Date getFechaAtencion() {
        return this.fechaAtencion;
    }
    
    public void setFechaAtencion(Date fechaAtencion) {
        this.fechaAtencion = fechaAtencion;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }




}


