package com.vitrocar.model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private int idPais;
     private String nombre;
     private String abreviacion;
     private Set<DomExtran> domExtrans = new HashSet<DomExtran>(0);
     private Set<Estado> estados = new HashSet<Estado>(0);

    public Pais() {
    }

	
    public Pais(int idPais) {
        this.idPais = idPais;
    }
    public Pais(int idPais, String nombre, String abreviacion, Set<DomExtran> domExtrans, Set<Estado> estados) {
       this.idPais = idPais;
       this.nombre = nombre;
       this.abreviacion = abreviacion;
       this.domExtrans = domExtrans;
       this.estados = estados;
    }
   
    public int getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(int idPais) {
        this.idPais = idPais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAbreviacion() {
        return this.abreviacion;
    }
    
    public void setAbreviacion(String abreviacion) {
        this.abreviacion = abreviacion;
    }
    public Set<DomExtran> getDomExtrans() {
        return this.domExtrans;
    }
    
    public void setDomExtrans(Set<DomExtran> domExtrans) {
        this.domExtrans = domExtrans;
    }
    public Set<Estado> getEstados() {
        return this.estados;
    }
    
    public void setEstados(Set<Estado> estados) {
        this.estados = estados;
    }




}


