package com.vitrocar.model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pieza generated by hbm2java
 */
public class Pieza  implements java.io.Serializable {


     private String claveNags;
     private CategoriaPieza categoriaPieza;
     private String nombre;
     private Double precio;
     private Set<DetOrdenServicio> detOrdenServicios = new HashSet<DetOrdenServicio>(0);
     private Set<AutoPieza> autoPiezas = new HashSet<AutoPieza>(0);

    public Pieza() {
    }

	
    public Pieza(String claveNags) {
        this.claveNags = claveNags;
    }
    public Pieza(String claveNags, CategoriaPieza categoriaPieza, String nombre, Double precio, Set<DetOrdenServicio> detOrdenServicios, Set<AutoPieza> autoPiezas) {
       this.claveNags = claveNags;
       this.categoriaPieza = categoriaPieza;
       this.nombre = nombre;
       this.precio = precio;
       this.detOrdenServicios = detOrdenServicios;
       this.autoPiezas = autoPiezas;
    }
   
    public String getClaveNags() {
        return this.claveNags;
    }
    
    public void setClaveNags(String claveNags) {
        this.claveNags = claveNags;
    }
    public CategoriaPieza getCategoriaPieza() {
        return this.categoriaPieza;
    }
    
    public void setCategoriaPieza(CategoriaPieza categoriaPieza) {
        this.categoriaPieza = categoriaPieza;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Set<DetOrdenServicio> getDetOrdenServicios() {
        return this.detOrdenServicios;
    }
    
    public void setDetOrdenServicios(Set<DetOrdenServicio> detOrdenServicios) {
        this.detOrdenServicios = detOrdenServicios;
    }
    public Set<AutoPieza> getAutoPiezas() {
        return this.autoPiezas;
    }
    
    public void setAutoPiezas(Set<AutoPieza> autoPiezas) {
        this.autoPiezas = autoPiezas;
    }




}


