package com.vitrocar.model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Siniestro generated by hbm2java
 */
public class Siniestro  implements java.io.Serializable {


     private int idSiniestro;
     private Aseguradora aseguradora;
     private Poliza poliza;
     private Date fechaAccidente;
     private Date horaAutorizacion;
     private Boolean autorizado;
     private String motivoRechazo;
     private String numReporte;
     private String claveSeg;
     private String otro;
     private String descripcionSuceso;
     private String telefono;
     private String seguimiento;
     private Date fechaReporte;
     private Set<OrdenServicio> ordenServicios = new HashSet<OrdenServicio>(0);
     private Set<DetSiniestro> detSiniestros = new HashSet<DetSiniestro>(0);

    public Siniestro() {
    }

	
    public Siniestro(int idSiniestro) {
        this.idSiniestro = idSiniestro;
    }
    public Siniestro(int idSiniestro, Aseguradora aseguradora, Poliza poliza, Date fechaAccidente, Date horaAutorizacion, Boolean autorizado, String motivoRechazo, String numReporte, String claveSeg, String otro, String descripcionSuceso, String telefono, String seguimiento, Date fechaReporte, Set<OrdenServicio> ordenServicios, Set<DetSiniestro> detSiniestros) {
       this.idSiniestro = idSiniestro;
       this.aseguradora = aseguradora;
       this.poliza = poliza;
       this.fechaAccidente = fechaAccidente;
       this.horaAutorizacion = horaAutorizacion;
       this.autorizado = autorizado;
       this.motivoRechazo = motivoRechazo;
       this.numReporte = numReporte;
       this.claveSeg = claveSeg;
       this.otro = otro;
       this.descripcionSuceso = descripcionSuceso;
       this.telefono = telefono;
       this.seguimiento = seguimiento;
       this.fechaReporte = fechaReporte;
       this.ordenServicios = ordenServicios;
       this.detSiniestros = detSiniestros;
    }
   
    public int getIdSiniestro() {
        return this.idSiniestro;
    }
    
    public void setIdSiniestro(int idSiniestro) {
        this.idSiniestro = idSiniestro;
    }
    public Aseguradora getAseguradora() {
        return this.aseguradora;
    }
    
    public void setAseguradora(Aseguradora aseguradora) {
        this.aseguradora = aseguradora;
    }
    public Poliza getPoliza() {
        return this.poliza;
    }
    
    public void setPoliza(Poliza poliza) {
        this.poliza = poliza;
    }
    public Date getFechaAccidente() {
        return this.fechaAccidente;
    }
    
    public void setFechaAccidente(Date fechaAccidente) {
        this.fechaAccidente = fechaAccidente;
    }
    public Date getHoraAutorizacion() {
        return this.horaAutorizacion;
    }
    
    public void setHoraAutorizacion(Date horaAutorizacion) {
        this.horaAutorizacion = horaAutorizacion;
    }
    public Boolean getAutorizado() {
        return this.autorizado;
    }
    
    public void setAutorizado(Boolean autorizado) {
        this.autorizado = autorizado;
    }
    public String getMotivoRechazo() {
        return this.motivoRechazo;
    }
    
    public void setMotivoRechazo(String motivoRechazo) {
        this.motivoRechazo = motivoRechazo;
    }
    public String getNumReporte() {
        return this.numReporte;
    }
    
    public void setNumReporte(String numReporte) {
        this.numReporte = numReporte;
    }
    public String getClaveSeg() {
        return this.claveSeg;
    }
    
    public void setClaveSeg(String claveSeg) {
        this.claveSeg = claveSeg;
    }
    public String getOtro() {
        return this.otro;
    }
    
    public void setOtro(String otro) {
        this.otro = otro;
    }
    public String getDescripcionSuceso() {
        return this.descripcionSuceso;
    }
    
    public void setDescripcionSuceso(String descripcionSuceso) {
        this.descripcionSuceso = descripcionSuceso;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getSeguimiento() {
        return this.seguimiento;
    }
    
    public void setSeguimiento(String seguimiento) {
        this.seguimiento = seguimiento;
    }
    public Date getFechaReporte() {
        return this.fechaReporte;
    }
    
    public void setFechaReporte(Date fechaReporte) {
        this.fechaReporte = fechaReporte;
    }
    public Set<OrdenServicio> getOrdenServicios() {
        return this.ordenServicios;
    }
    
    public void setOrdenServicios(Set<OrdenServicio> ordenServicios) {
        this.ordenServicios = ordenServicios;
    }
    public Set<DetSiniestro> getDetSiniestros() {
        return this.detSiniestros;
    }
    
    public void setDetSiniestros(Set<DetSiniestro> detSiniestros) {
        this.detSiniestros = detSiniestros;
    }




}


