package com.vitrocar.model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal  implements java.io.Serializable {


     private int idSucursal;
     private String nombre;
     private String direccion;
     private String abreviacion;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Sucursal() {
    }

	
    public Sucursal(int idSucursal) {
        this.idSucursal = idSucursal;
    }
    public Sucursal(int idSucursal, String nombre, String direccion, String abreviacion, Set<Empleado> empleados) {
       this.idSucursal = idSucursal;
       this.nombre = nombre;
       this.direccion = direccion;
       this.abreviacion = abreviacion;
       this.empleados = empleados;
    }
   
    public int getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(int idSucursal) {
        this.idSucursal = idSucursal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getAbreviacion() {
        return this.abreviacion;
    }
    
    public void setAbreviacion(String abreviacion) {
        this.abreviacion = abreviacion;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


