package com.vitrocar.model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoLic generated by hbm2java
 */
public class TipoLic  implements java.io.Serializable {


     private int idTipo;
     private String nombre;
     private Set<Conductor> conductors = new HashSet<Conductor>(0);

    public TipoLic() {
    }

	
    public TipoLic(int idTipo) {
        this.idTipo = idTipo;
    }
    public TipoLic(int idTipo, String nombre, Set<Conductor> conductors) {
       this.idTipo = idTipo;
       this.nombre = nombre;
       this.conductors = conductors;
    }
   
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Conductor> getConductors() {
        return this.conductors;
    }
    
    public void setConductors(Set<Conductor> conductors) {
        this.conductors = conductors;
    }




}


