package com.vitrocar.model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoAuto generated by hbm2java
 */
public class TipoAuto  implements java.io.Serializable {


     private int idTipoAuto;
     private String descripcion;
     private Set<Auto> autos = new HashSet<Auto>(0);

    public TipoAuto() {
    }

	
    public TipoAuto(int idTipoAuto) {
        this.idTipoAuto = idTipoAuto;
    }
    public TipoAuto(int idTipoAuto, String descripcion, Set<Auto> autos) {
       this.idTipoAuto = idTipoAuto;
       this.descripcion = descripcion;
       this.autos = autos;
    }
   
    public int getIdTipoAuto() {
        return this.idTipoAuto;
    }
    
    public void setIdTipoAuto(int idTipoAuto) {
        this.idTipoAuto = idTipoAuto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Auto> getAutos() {
        return this.autos;
    }
    
    public void setAutos(Set<Auto> autos) {
        this.autos = autos;
    }




}


