package model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1



/**
 * Anio generated by hbm2java
 */
public class Anio  implements java.io.Serializable {


     private int idAnio;
     private Integer anio;

    public Anio() {
    }

	
    public Anio(int idAnio) {
        this.idAnio = idAnio;
    }
    public Anio(int idAnio, Integer anio) {
       this.idAnio = idAnio;
       this.anio = anio;
    }
   
    public int getIdAnio() {
        return this.idAnio;
    }
    
    public void setIdAnio(int idAnio) {
        this.idAnio = idAnio;
    }
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }




}


