package model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1



/**
 * Calif generated by hbm2java
 */
public class Calif  implements java.io.Serializable {


     private int idCalif;
     private Empleado empleadoByIdVendedor;
     private Empleado empleadoByIdCalificador;
     private Empleado empleadoByIdTecnico;
     private OrdenServicio ordenServicio;
     private Boolean lda;
     private Boolean ldadt;
     private Boolean ads;
     private Boolean adt;
     private Boolean cdtde;

    public Calif() {
    }

	
    public Calif(int idCalif) {
        this.idCalif = idCalif;
    }
    public Calif(int idCalif, Empleado empleadoByIdVendedor, Empleado empleadoByIdCalificador, Empleado empleadoByIdTecnico, OrdenServicio ordenServicio, Boolean lda, Boolean ldadt, Boolean ads, Boolean adt, Boolean cdtde) {
       this.idCalif = idCalif;
       this.empleadoByIdVendedor = empleadoByIdVendedor;
       this.empleadoByIdCalificador = empleadoByIdCalificador;
       this.empleadoByIdTecnico = empleadoByIdTecnico;
       this.ordenServicio = ordenServicio;
       this.lda = lda;
       this.ldadt = ldadt;
       this.ads = ads;
       this.adt = adt;
       this.cdtde = cdtde;
    }
   
    public int getIdCalif() {
        return this.idCalif;
    }
    
    public void setIdCalif(int idCalif) {
        this.idCalif = idCalif;
    }
    public Empleado getEmpleadoByIdVendedor() {
        return this.empleadoByIdVendedor;
    }
    
    public void setEmpleadoByIdVendedor(Empleado empleadoByIdVendedor) {
        this.empleadoByIdVendedor = empleadoByIdVendedor;
    }
    public Empleado getEmpleadoByIdCalificador() {
        return this.empleadoByIdCalificador;
    }
    
    public void setEmpleadoByIdCalificador(Empleado empleadoByIdCalificador) {
        this.empleadoByIdCalificador = empleadoByIdCalificador;
    }
    public Empleado getEmpleadoByIdTecnico() {
        return this.empleadoByIdTecnico;
    }
    
    public void setEmpleadoByIdTecnico(Empleado empleadoByIdTecnico) {
        this.empleadoByIdTecnico = empleadoByIdTecnico;
    }
    public OrdenServicio getOrdenServicio() {
        return this.ordenServicio;
    }
    
    public void setOrdenServicio(OrdenServicio ordenServicio) {
        this.ordenServicio = ordenServicio;
    }
    public Boolean getLda() {
        return this.lda;
    }
    
    public void setLda(Boolean lda) {
        this.lda = lda;
    }
    public Boolean getLdadt() {
        return this.ldadt;
    }
    
    public void setLdadt(Boolean ldadt) {
        this.ldadt = ldadt;
    }
    public Boolean getAds() {
        return this.ads;
    }
    
    public void setAds(Boolean ads) {
        this.ads = ads;
    }
    public Boolean getAdt() {
        return this.adt;
    }
    
    public void setAdt(Boolean adt) {
        this.adt = adt;
    }
    public Boolean getCdtde() {
        return this.cdtde;
    }
    
    public void setCdtde(Boolean cdtde) {
        this.cdtde = cdtde;
    }




}


