package model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1



/**
 * Cod generated by hbm2java
 */
public class Cod  implements java.io.Serializable {


     private int idCod;
     private OrdenServicio ordenServicio;
     private Boolean ife;
     private Boolean licencia;
     private Boolean tarjetaCirculacion;
     private Boolean poliza;
     private Boolean placas;
     private Boolean engomado;
     private String motivo;

    public Cod() {
    }

	
    public Cod(int idCod) {
        this.idCod = idCod;
    }
    public Cod(int idCod, OrdenServicio ordenServicio, Boolean ife, Boolean licencia, Boolean tarjetaCirculacion, Boolean poliza, Boolean placas, Boolean engomado, String motivo) {
       this.idCod = idCod;
       this.ordenServicio = ordenServicio;
       this.ife = ife;
       this.licencia = licencia;
       this.tarjetaCirculacion = tarjetaCirculacion;
       this.poliza = poliza;
       this.placas = placas;
       this.engomado = engomado;
       this.motivo = motivo;
    }
   
    public int getIdCod() {
        return this.idCod;
    }
    
    public void setIdCod(int idCod) {
        this.idCod = idCod;
    }
    public OrdenServicio getOrdenServicio() {
        return this.ordenServicio;
    }
    
    public void setOrdenServicio(OrdenServicio ordenServicio) {
        this.ordenServicio = ordenServicio;
    }
    public Boolean getIfe() {
        return this.ife;
    }
    
    public void setIfe(Boolean ife) {
        this.ife = ife;
    }
    public Boolean getLicencia() {
        return this.licencia;
    }
    
    public void setLicencia(Boolean licencia) {
        this.licencia = licencia;
    }
    public Boolean getTarjetaCirculacion() {
        return this.tarjetaCirculacion;
    }
    
    public void setTarjetaCirculacion(Boolean tarjetaCirculacion) {
        this.tarjetaCirculacion = tarjetaCirculacion;
    }
    public Boolean getPoliza() {
        return this.poliza;
    }
    
    public void setPoliza(Boolean poliza) {
        this.poliza = poliza;
    }
    public Boolean getPlacas() {
        return this.placas;
    }
    
    public void setPlacas(Boolean placas) {
        this.placas = placas;
    }
    public Boolean getEngomado() {
        return this.engomado;
    }
    
    public void setEngomado(Boolean engomado) {
        this.engomado = engomado;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }




}


