package model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Conductor generated by hbm2java
 */
public class Conductor  implements java.io.Serializable {


     private int idConductor;
     private TipoLic tipoLic;
     private Uso uso;
     private String nombre;
     private Date inicioLic;
     private Date finLic;
     private String lugarExp;
     private Integer numInt;
     private Integer numExt;
     private String colonia;
     private String calle;

    public Conductor() {
    }

	
    public Conductor(int idConductor) {
        this.idConductor = idConductor;
    }
    public Conductor(int idConductor, TipoLic tipoLic, Uso uso, String nombre, Date inicioLic, Date finLic, String lugarExp, Integer numInt, Integer numExt, String colonia, String calle) {
       this.idConductor = idConductor;
       this.tipoLic = tipoLic;
       this.uso = uso;
       this.nombre = nombre;
       this.inicioLic = inicioLic;
       this.finLic = finLic;
       this.lugarExp = lugarExp;
       this.numInt = numInt;
       this.numExt = numExt;
       this.colonia = colonia;
       this.calle = calle;
    }
   
    public int getIdConductor() {
        return this.idConductor;
    }
    
    public void setIdConductor(int idConductor) {
        this.idConductor = idConductor;
    }
    public TipoLic getTipoLic() {
        return this.tipoLic;
    }
    
    public void setTipoLic(TipoLic tipoLic) {
        this.tipoLic = tipoLic;
    }
    public Uso getUso() {
        return this.uso;
    }
    
    public void setUso(Uso uso) {
        this.uso = uso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getInicioLic() {
        return this.inicioLic;
    }
    
    public void setInicioLic(Date inicioLic) {
        this.inicioLic = inicioLic;
    }
    public Date getFinLic() {
        return this.finLic;
    }
    
    public void setFinLic(Date finLic) {
        this.finLic = finLic;
    }
    public String getLugarExp() {
        return this.lugarExp;
    }
    
    public void setLugarExp(String lugarExp) {
        this.lugarExp = lugarExp;
    }
    public Integer getNumInt() {
        return this.numInt;
    }
    
    public void setNumInt(Integer numInt) {
        this.numInt = numInt;
    }
    public Integer getNumExt() {
        return this.numExt;
    }
    
    public void setNumExt(Integer numExt) {
        this.numExt = numExt;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }




}


