package model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cp generated by hbm2java
 */
public class Cp  implements java.io.Serializable {


     private int idCp;
     private Municipio municipio;
     private Set<DatosCliente> datosClientes = new HashSet<DatosCliente>(0);
     private Set<Facturacion> facturacions = new HashSet<Facturacion>(0);

    public Cp() {
    }

	
    public Cp(int idCp) {
        this.idCp = idCp;
    }
    public Cp(int idCp, Municipio municipio, Set<DatosCliente> datosClientes, Set<Facturacion> facturacions) {
       this.idCp = idCp;
       this.municipio = municipio;
       this.datosClientes = datosClientes;
       this.facturacions = facturacions;
    }
   
    public int getIdCp() {
        return this.idCp;
    }
    
    public void setIdCp(int idCp) {
        this.idCp = idCp;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public Set<DatosCliente> getDatosClientes() {
        return this.datosClientes;
    }
    
    public void setDatosClientes(Set<DatosCliente> datosClientes) {
        this.datosClientes = datosClientes;
    }
    public Set<Facturacion> getFacturacions() {
        return this.facturacions;
    }
    
    public void setFacturacions(Set<Facturacion> facturacions) {
        this.facturacions = facturacions;
    }




}


