package model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DatosCliente generated by hbm2java
 */
public class DatosCliente  implements java.io.Serializable {


     private String rfc;
     private Cliente cliente;
     private Cp cp;
     private Date fechaNac;
     private String nacionalidad;
     private String profesion;
     private String actGiro;
     private String curp;
     private String colonia;
     private Integer numInt;
     private Integer numExt;

    public DatosCliente() {
    }

	
    public DatosCliente(String rfc) {
        this.rfc = rfc;
    }
    public DatosCliente(String rfc, Cliente cliente, Cp cp, Date fechaNac, String nacionalidad, String profesion, String actGiro, String curp, String colonia, Integer numInt, Integer numExt) {
       this.rfc = rfc;
       this.cliente = cliente;
       this.cp = cp;
       this.fechaNac = fechaNac;
       this.nacionalidad = nacionalidad;
       this.profesion = profesion;
       this.actGiro = actGiro;
       this.curp = curp;
       this.colonia = colonia;
       this.numInt = numInt;
       this.numExt = numExt;
    }
   
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Cp getCp() {
        return this.cp;
    }
    
    public void setCp(Cp cp) {
        this.cp = cp;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }
    public String getActGiro() {
        return this.actGiro;
    }
    
    public void setActGiro(String actGiro) {
        this.actGiro = actGiro;
    }
    public String getCurp() {
        return this.curp;
    }
    
    public void setCurp(String curp) {
        this.curp = curp;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public Integer getNumInt() {
        return this.numInt;
    }
    
    public void setNumInt(Integer numInt) {
        this.numInt = numInt;
    }
    public Integer getNumExt() {
        return this.numExt;
    }
    
    public void setNumExt(Integer numExt) {
        this.numExt = numExt;
    }




}


