package model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1



/**
 * DetOrdenServicio generated by hbm2java
 */
public class DetOrdenServicio  implements java.io.Serializable {


     private DetOrdenServicioId id;
     private OrdenServicio ordenServicio;
     private Pieza pieza;
     private Servicio servicio;
     private Integer cantidad;

    public DetOrdenServicio() {
    }

	
    public DetOrdenServicio(DetOrdenServicioId id, OrdenServicio ordenServicio) {
        this.id = id;
        this.ordenServicio = ordenServicio;
    }
    public DetOrdenServicio(DetOrdenServicioId id, OrdenServicio ordenServicio, Pieza pieza, Servicio servicio, Integer cantidad) {
       this.id = id;
       this.ordenServicio = ordenServicio;
       this.pieza = pieza;
       this.servicio = servicio;
       this.cantidad = cantidad;
    }
   
    public DetOrdenServicioId getId() {
        return this.id;
    }
    
    public void setId(DetOrdenServicioId id) {
        this.id = id;
    }
    public OrdenServicio getOrdenServicio() {
        return this.ordenServicio;
    }
    
    public void setOrdenServicio(OrdenServicio ordenServicio) {
        this.ordenServicio = ordenServicio;
    }
    public Pieza getPieza() {
        return this.pieza;
    }
    
    public void setPieza(Pieza pieza) {
        this.pieza = pieza;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


