package model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int idEmpleado;
     private Puesto puesto;
     private Sucursal sucursal;
     private String nombre;
     private String direccion;
     private String users;
     private String passwd;
     private Set<Calif> califsForIdVendedor = new HashSet<Calif>(0);
     private Set<OrdenServicio> ordenServiciosForAtendio = new HashSet<OrdenServicio>(0);
     private Set<OrdenServicio> ordenServiciosForInstalador = new HashSet<OrdenServicio>(0);
     private Set<Calif> califsForIdCalificador = new HashSet<Calif>(0);
     private Set<Calif> califsForIdTecnico = new HashSet<Calif>(0);

    public Empleado() {
    }

	
    public Empleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Empleado(int idEmpleado, Puesto puesto, Sucursal sucursal, String nombre, String direccion, String users, String passwd, Set<Calif> califsForIdVendedor, Set<OrdenServicio> ordenServiciosForAtendio, Set<OrdenServicio> ordenServiciosForInstalador, Set<Calif> califsForIdCalificador, Set<Calif> califsForIdTecnico) {
       this.idEmpleado = idEmpleado;
       this.puesto = puesto;
       this.sucursal = sucursal;
       this.nombre = nombre;
       this.direccion = direccion;
       this.users = users;
       this.passwd = passwd;
       this.califsForIdVendedor = califsForIdVendedor;
       this.ordenServiciosForAtendio = ordenServiciosForAtendio;
       this.ordenServiciosForInstalador = ordenServiciosForInstalador;
       this.califsForIdCalificador = califsForIdCalificador;
       this.califsForIdTecnico = califsForIdTecnico;
    }
   
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Puesto getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(Puesto puesto) {
        this.puesto = puesto;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getUsers() {
        return this.users;
    }
    
    public void setUsers(String users) {
        this.users = users;
    }
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
    public Set<Calif> getCalifsForIdVendedor() {
        return this.califsForIdVendedor;
    }
    
    public void setCalifsForIdVendedor(Set<Calif> califsForIdVendedor) {
        this.califsForIdVendedor = califsForIdVendedor;
    }
    public Set<OrdenServicio> getOrdenServiciosForAtendio() {
        return this.ordenServiciosForAtendio;
    }
    
    public void setOrdenServiciosForAtendio(Set<OrdenServicio> ordenServiciosForAtendio) {
        this.ordenServiciosForAtendio = ordenServiciosForAtendio;
    }
    public Set<OrdenServicio> getOrdenServiciosForInstalador() {
        return this.ordenServiciosForInstalador;
    }
    
    public void setOrdenServiciosForInstalador(Set<OrdenServicio> ordenServiciosForInstalador) {
        this.ordenServiciosForInstalador = ordenServiciosForInstalador;
    }
    public Set<Calif> getCalifsForIdCalificador() {
        return this.califsForIdCalificador;
    }
    
    public void setCalifsForIdCalificador(Set<Calif> califsForIdCalificador) {
        this.califsForIdCalificador = califsForIdCalificador;
    }
    public Set<Calif> getCalifsForIdTecnico() {
        return this.califsForIdTecnico;
    }
    
    public void setCalifsForIdTecnico(Set<Calif> califsForIdTecnico) {
        this.califsForIdTecnico = califsForIdTecnico;
    }




}


