package model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private int idEstado;
     private Pais pais;
     private String nombre;
     private Set<Municipio> municipios = new HashSet<Municipio>(0);

    public Estado() {
    }

	
    public Estado(int idEstado) {
        this.idEstado = idEstado;
    }
    public Estado(int idEstado, Pais pais, String nombre, Set<Municipio> municipios) {
       this.idEstado = idEstado;
       this.pais = pais;
       this.nombre = nombre;
       this.municipios = municipios;
    }
   
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Municipio> getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Set<Municipio> municipios) {
        this.municipios = municipios;
    }




}


