package model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private int idMunicipio;
     private Estado estado;
     private String nombre;
     private Set<Cp> cps = new HashSet<Cp>(0);

    public Municipio() {
    }

	
    public Municipio(int idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public Municipio(int idMunicipio, Estado estado, String nombre, Set<Cp> cps) {
       this.idMunicipio = idMunicipio;
       this.estado = estado;
       this.nombre = nombre;
       this.cps = cps;
    }
   
    public int getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(int idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Cp> getCps() {
        return this.cps;
    }
    
    public void setCps(Set<Cp> cps) {
        this.cps = cps;
    }




}


