package model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenServicio generated by hbm2java
 */
public class OrdenServicio  implements java.io.Serializable {


     private String folio;
     private Empleado empleadoByAtendio;
     private Empleado empleadoByInstalador;
     private Siniestro siniestro;
     private TipoAtencion tipoAtencion;
     private Date fecha;
     private Date horaInicio;
     private Date horaFin;
     private Date horaAsignacion;
     private Set<Cod> cods = new HashSet<Cod>(0);
     private Set<Istable> istables = new HashSet<Istable>(0);
     private Set<Rppd> rppds = new HashSet<Rppd>(0);
     private Set<Calif> califs = new HashSet<Calif>(0);
     private Set<DetOrdenServicio> detOrdenServicios = new HashSet<DetOrdenServicio>(0);

    public OrdenServicio() {
    }

	
    public OrdenServicio(String folio) {
        this.folio = folio;
    }
    public OrdenServicio(String folio, Empleado empleadoByAtendio, Empleado empleadoByInstalador, Siniestro siniestro, TipoAtencion tipoAtencion, Date fecha, Date horaInicio, Date horaFin, Date horaAsignacion, Set<Cod> cods, Set<Istable> istables, Set<Rppd> rppds, Set<Calif> califs, Set<DetOrdenServicio> detOrdenServicios) {
       this.folio = folio;
       this.empleadoByAtendio = empleadoByAtendio;
       this.empleadoByInstalador = empleadoByInstalador;
       this.siniestro = siniestro;
       this.tipoAtencion = tipoAtencion;
       this.fecha = fecha;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
       this.horaAsignacion = horaAsignacion;
       this.cods = cods;
       this.istables = istables;
       this.rppds = rppds;
       this.califs = califs;
       this.detOrdenServicios = detOrdenServicios;
    }
   
    public String getFolio() {
        return this.folio;
    }
    
    public void setFolio(String folio) {
        this.folio = folio;
    }
    public Empleado getEmpleadoByAtendio() {
        return this.empleadoByAtendio;
    }
    
    public void setEmpleadoByAtendio(Empleado empleadoByAtendio) {
        this.empleadoByAtendio = empleadoByAtendio;
    }
    public Empleado getEmpleadoByInstalador() {
        return this.empleadoByInstalador;
    }
    
    public void setEmpleadoByInstalador(Empleado empleadoByInstalador) {
        this.empleadoByInstalador = empleadoByInstalador;
    }
    public Siniestro getSiniestro() {
        return this.siniestro;
    }
    
    public void setSiniestro(Siniestro siniestro) {
        this.siniestro = siniestro;
    }
    public TipoAtencion getTipoAtencion() {
        return this.tipoAtencion;
    }
    
    public void setTipoAtencion(TipoAtencion tipoAtencion) {
        this.tipoAtencion = tipoAtencion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }
    public Date getHoraAsignacion() {
        return this.horaAsignacion;
    }
    
    public void setHoraAsignacion(Date horaAsignacion) {
        this.horaAsignacion = horaAsignacion;
    }
    public Set<Cod> getCods() {
        return this.cods;
    }
    
    public void setCods(Set<Cod> cods) {
        this.cods = cods;
    }
    public Set<Istable> getIstables() {
        return this.istables;
    }
    
    public void setIstables(Set<Istable> istables) {
        this.istables = istables;
    }
    public Set<Rppd> getRppds() {
        return this.rppds;
    }
    
    public void setRppds(Set<Rppd> rppds) {
        this.rppds = rppds;
    }
    public Set<Calif> getCalifs() {
        return this.califs;
    }
    
    public void setCalifs(Set<Calif> califs) {
        this.califs = califs;
    }
    public Set<DetOrdenServicio> getDetOrdenServicios() {
        return this.detOrdenServicios;
    }
    
    public void setDetOrdenServicios(Set<DetOrdenServicio> detOrdenServicios) {
        this.detOrdenServicios = detOrdenServicios;
    }




}


