package model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Puesto generated by hbm2java
 */
public class Puesto  implements java.io.Serializable {


     private int idPuesto;
     private String nombre;
     private String descripcion;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Puesto() {
    }

	
    public Puesto(int idPuesto) {
        this.idPuesto = idPuesto;
    }
    public Puesto(int idPuesto, String nombre, String descripcion, Set<Empleado> empleados) {
       this.idPuesto = idPuesto;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.empleados = empleados;
    }
   
    public int getIdPuesto() {
        return this.idPuesto;
    }
    
    public void setIdPuesto(int idPuesto) {
        this.idPuesto = idPuesto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


