package model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private int idServicio;
     private String nombre;
     private String descripcion;
     private Date tiempo;
     private Set<DetOrdenServicio> detOrdenServicios = new HashSet<DetOrdenServicio>(0);

    public Servicio() {
    }

	
    public Servicio(int idServicio) {
        this.idServicio = idServicio;
    }
    public Servicio(int idServicio, String nombre, String descripcion, Date tiempo, Set<DetOrdenServicio> detOrdenServicios) {
       this.idServicio = idServicio;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.tiempo = tiempo;
       this.detOrdenServicios = detOrdenServicios;
    }
   
    public int getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(int idServicio) {
        this.idServicio = idServicio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(Date tiempo) {
        this.tiempo = tiempo;
    }
    public Set<DetOrdenServicio> getDetOrdenServicios() {
        return this.detOrdenServicios;
    }
    
    public void setDetOrdenServicios(Set<DetOrdenServicio> detOrdenServicios) {
        this.detOrdenServicios = detOrdenServicios;
    }




}


