package model;
// Generated 17/08/2018 01:32:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoAtencion generated by hbm2java
 */
public class TipoAtencion  implements java.io.Serializable {


     private int idTipoAtencion;
     private String nombre;
     private Set<OrdenServicio> ordenServicios = new HashSet<OrdenServicio>(0);

    public TipoAtencion() {
    }

	
    public TipoAtencion(int idTipoAtencion) {
        this.idTipoAtencion = idTipoAtencion;
    }
    public TipoAtencion(int idTipoAtencion, String nombre, Set<OrdenServicio> ordenServicios) {
       this.idTipoAtencion = idTipoAtencion;
       this.nombre = nombre;
       this.ordenServicios = ordenServicios;
    }
   
    public int getIdTipoAtencion() {
        return this.idTipoAtencion;
    }
    
    public void setIdTipoAtencion(int idTipoAtencion) {
        this.idTipoAtencion = idTipoAtencion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<OrdenServicio> getOrdenServicios() {
        return this.ordenServicios;
    }
    
    public void setOrdenServicios(Set<OrdenServicio> ordenServicios) {
        this.ordenServicios = ordenServicios;
    }




}


